### ISSUE TITLE
Extend x509cert search methods

### ISSUE THREAD

**Issue by Phoedoth** [yallie/MdlpClient#13]
Добрый день, спасибо за отличную библиотеку. Не очень понял только с поиском сертификатов для подписи. Ищется user_id в subject и thumbprint сертификата. В рабочей системе никак не изменить ни одно из трех значений, как и не задать сертификат для подключения явно.

Вижу пути решения:
1) свойство MdlpApiClient.MdlpClient.UserCertificate сделать public
2) добавить параметр x509Certificate в методы Authenticate() класса ResidentCredentials

**Comment by yallie** [comment]
Добрый день! 

Не вполне понял вашу ситуацию.
Вы хотите подписывать документы не тем сертификатом, которым аутентифицировались, а каким-то другим?

**Comment by Phoedoth** [comment]
Нет, хочу просто при аутентификации явно указать сертификат.

**Comment by yallie** [comment]
Ок, можно в ResidentCredentials добавить возможность указывать явно сам сертификат.
Только я все-таки не понимаю, почему в вашем случае нельзя указать отпечаток сертификата в UserID?
Библиотека не может отыскать установленный сертификат по его отпечатку?

Возможно, дело в том, что сертификат по умолчанию ищется в StoreLocation.LocalMachine.
Вы не пробовали переключить поиск на StoreLocation.CurrentUser? Вот так:

```c#
// где-нибудь перед созданием MdlpClient
GostCryptoHelpers.DefaultStoreLocation = StoreLocation.CurrentUser;
```

**Comment by Phoedoth** [comment]
Так ведь UserID назначает честный знак. Отпечаток для сертификата назначает удостоверяющий центр. Насколько я понял, сертификат не находится потому что:
userID <> thumbprint.

**Comment by yallie** [comment]
**TL/DR: передавайте в этом поле thumbprint сертификата в виде hex-строчки.**

Это поле в [API Честного знака](https://xn--80ajghhoc2aj1c8b.xn--p1ai/upload/iblock/200/IS-_Markirovka_.-MDLP.-Protokol-obmena-interfeysnogo-urovnya-v3.07.pdf) не очень удачно названо UserID.
Там передается не внутренний идентификатор пользователя, 
а отпечаток сертификата (для резидента), либо email (для нерезидента):

![image](https://user-images.githubusercontent.com/672878/86896960-77fd9880-c10f-11ea-9042-643804ce80e6.png)

В самом деле, хрен его знает, как такое поле правильно называть.
Так что я просто оставил терминологию официальной документации.

**Comment by Phoedoth** [comment]
Точно, а я всегда userID передавал, и тоже подключался...

**Comment by yallie** [comment]
А, вот оно что!
Я не знал, что по коду пользователя оно тоже авторизует.
Недокументированная возможность :)
